import pandas as pd
import requests
import io

def fetch_google_sheet_csv(url, sheet_name=None):
    """Fetch CSV data from a specific sheet in a Google Sheet."""
    if sheet_name:
        sheet_url = f"{url}&sheet={sheet_name}"
    else:
        sheet_url = url
    response = requests.get(sheet_url)
    response.raise_for_status()
    # Google's CSV export declares no charset, so requests falls back to
    # ISO-8859-1 and mangles accented characters. The export is always UTF-8.
    response.encoding = "utf-8"
    return pd.read_csv(io.StringIO(response.text))

# def fetch_google_sheet_csv(url):
#    """Fetch CSV data from a public Google Sheet."""
#    response = requests.get(url)
#    response.raise_for_status()
#    return pd.read_csv(io.StringIO(response.text))

def update_markdown(df, filename="README.md"):
    """Convert DataFrame to Markdown and write the schedule page."""
    with open(filename, 'w', encoding='utf-8') as f:

        df = df.fillna("")
        f.write("# BMI PhD Student Meeting Schedule — Fall 2026\n\n")
        f.write("> _Auto-generated from the BMI Google Sheet — do not edit this file by hand._\n\n")
        f.write("**To update, see [how-to-update.md](how-to-update.md).**\n\n")

        f.write(df.to_markdown(index=False))
        f.write("\n")
    print(f"{filename} has been updated.")

if __name__ == "__main__":
    # Use the CSV export link for your Google Sheet
    CSV_URL = "https://docs.google.com/spreadsheets/d/1F0RBQgT-QfFQ9y8XKu8jGP-HMpRstzrGFnQtkEQJesI/export?format=csv&gid=0"
    #df = fetch_google_sheet_csv(CSV_URL)
    df = fetch_google_sheet_csv(CSV_URL, sheet_name='2026')

    update_markdown(df)
